// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc308.FRC2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;
import com.ctre.CANTalon;


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon chassisCANTalon_1 = new CANTalon(1);
    public static CANTalon chassisCANTalon_2= new CANTalon(2);
    public static CANTalon chassisCANTalon_3= new CANTalon(3);
    public static CANTalon chassisCANTalon_4= new CANTalon(4);
    public static CANTalon chassisCANTalon_5= new CANTalon(5);
    public static CANTalon chassisCANTalon_6= new CANTalon(6);
    public static RobotDrive chassisRobotDrive6;
    public static AnalogGyro chassisAnalogGyro1;
    public static CANTalon intakeCANTalon_Ball_1 = new CANTalon(15);
    public static CANTalon intakeCANTalon_Ball_2 = new CANTalon(16);
    public static CANTalon intakeCANTalon_Gear_1 = new CANTalon(17);
    public static Solenoid gearDeliverySolenoid_1;
    public static Solenoid gearDeliverySolenoid_2;
    public static CANTalon climbCANTalon = new CANTalon(20);
    public static CANTalon processBallsCANTalon = new CANTalon(19);
    public static CANTalon shooterCANTalon_1 = new CANTalon(10);
    public static Compressor pneumaticsCompressor = new Compressor(0);

    

    public static void init() {
    	
    	

        chassisRobotDrive6 = new RobotDrive(chassisCANTalon_1, chassisCANTalon_2
              ,chassisCANTalon_4, chassisCANTalon_5 );
        
        chassisRobotDrive6.setSafetyEnabled(false);
        chassisRobotDrive6.setExpiration(0.1);
        chassisRobotDrive6.setSensitivity(0.5);
        chassisRobotDrive6.setMaxOutput(1.0);
        
        
        gearDeliverySolenoid_1 = new Solenoid(0, 0);
        LiveWindow.addActuator("GearDelivery", " Gear Solenoid 1", gearDeliverySolenoid_1);
        
        gearDeliverySolenoid_2 = new Solenoid(0, 1);
        LiveWindow.addActuator("GearDelivery", "Gear Solenoid 2", gearDeliverySolenoid_2);
        
    }
}
