// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc308.FRC2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Solenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon chassisCANTalon1;
    public static CANTalon chassisCANTalon2;
    public static CANTalon chassisCANTalon4;
    public static CANTalon chassisCANTalon5;
    public static RobotDrive chassisRobotDrive6;
    public static CANTalon chassisCANTalon3;
    public static CANTalon chassisCANTalon6;
    public static AnalogGyro chassisAnalogGyro1;
    public static CANTalon intakeCANTalon17;
    public static CANTalon intakeCANTalon16;
    public static CANTalon intakeCANTalon15;
    public static Solenoid gearDeliverySolenoid1;
    public static Solenoid gearDeliverySolenoid2;
    public static CANTalon climbCANTalon20;
    public static CANTalon processBallsCANTalon19;
    public static CANTalon shooterCANTalon10;
    public static Compressor pneumaticsCompressor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        chassisCANTalon1 = new CANTalon(1);
        LiveWindow.addActuator("Chassis", "CAN Talon 1", chassisCANTalon1);
        
        chassisCANTalon2 = new CANTalon(2);
        LiveWindow.addActuator("Chassis", "CAN Talon 2", chassisCANTalon2);
        
        chassisCANTalon4 = new CANTalon(4);
        LiveWindow.addActuator("Chassis", "CAN Talon 4", chassisCANTalon4);
        
        chassisCANTalon5 = new CANTalon(5);
        LiveWindow.addActuator("Chassis", "CAN Talon 5", chassisCANTalon5);
        
        chassisRobotDrive6 = new RobotDrive(chassisCANTalon1, chassisCANTalon2,
              chassisCANTalon4, chassisCANTalon5);
        
        chassisRobotDrive6.setSafetyEnabled(true);
        chassisRobotDrive6.setExpiration(0.1);
        chassisRobotDrive6.setSensitivity(0.5);
        chassisRobotDrive6.setMaxOutput(1.0);

        chassisCANTalon3 = new CANTalon(3);
        LiveWindow.addActuator("Chassis", "CAN Talon 3", chassisCANTalon3);
        
        chassisCANTalon6 = new CANTalon(6);
        LiveWindow.addActuator("Chassis", "CAN Talon 6", chassisCANTalon6);
        
        chassisAnalogGyro1 = new AnalogGyro(0);
        LiveWindow.addSensor("Chassis", "AnalogGyro 1", chassisAnalogGyro1);
        chassisAnalogGyro1.setSensitivity(0.007);
        intakeCANTalon17 = new CANTalon(17);
        LiveWindow.addActuator("Intake", "CAN Talon 17", intakeCANTalon17);
        
        intakeCANTalon16 = new CANTalon(16);
        LiveWindow.addActuator("Intake", "CAN Talon 16", intakeCANTalon16);
        
        intakeCANTalon15 = new CANTalon(15);
        LiveWindow.addActuator("Intake", "CAN Talon 15", intakeCANTalon15);
        
        gearDeliverySolenoid1 = new Solenoid(0, 0);
        LiveWindow.addActuator("GearDelivery", "Solenoid 1", gearDeliverySolenoid1);
        
        gearDeliverySolenoid2 = new Solenoid(0, 1);
        LiveWindow.addActuator("GearDelivery", "Solenoid 2", gearDeliverySolenoid2);
        
        climbCANTalon20 = new CANTalon(20);
        LiveWindow.addActuator("Climb", "CAN Talon 20", climbCANTalon20);
        
        processBallsCANTalon19 = new CANTalon(19);
        LiveWindow.addActuator("ProcessBalls", "CAN Talon 19", processBallsCANTalon19);
        
        shooterCANTalon10 = new CANTalon(10);
        LiveWindow.addActuator("Shooter", "CAN Talon 10", shooterCANTalon10);
        
        pneumaticsCompressor = new Compressor(0);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
