
package org.usfirst.frc308.FRC2017.subsystems;

import org.usfirst.frc308.FRC2017.RobotMap;
import org.usfirst.frc308.FRC2017.commands.*;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Vision extends Subsystem {


	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		setDefaultCommand(new VisionProcessing());


	}

	public int getLargestIndex(double[] input) {
		if (input.length == 0) {
			return -1;
		}
		int biggest = 0;
		for (int i = 1; i < input.length; i++) {
			if (input[i] > input[biggest]) {
				biggest = i;
			}
		}
		return biggest;
	}
}
